spring:
  data:
    cassandra:
      keyspace-name: db_springboot_backend
      contact-points: localhost
      port: 9042
  jackson:
    time-zone: America/Lima
    locale: es_PE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


